import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/context/theme-provider";
import { MainNavigation } from "@/components/layout/main-navigation";
import { Background } from "@/components/common/Background";
import { ScrollArea } from "@/components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={inter.className}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <ScrollArea className="h-screen">
                            <Background />
                            <header>
                                <MainNavigation />
                            </header>
                            {children}
                            <footer className="my-20"></footer>
                        </ScrollArea>
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
